# kali-build/main.yml
- name: "Customizing Ubuntu"
  hosts: localhost
  connection: local
  roles:
    - role: "tools-installation"
    - role: "terminal-setup"
    - role: "browser-settings"
    - role: "nvim-setup"
    - role: "gnome-settings"
    - role: "pictures-copy"
#     - role: "logging-setup"

