# roles/nvim-setup/tasks/install_nvim_deb.yml

- name: Download Neovim 0.9.5 tarball
  get_url:
    url: "https://github.com/neovim/neovim/releases/download/v0.9.5/nvim-linux64.tar.gz"
    dest: "/tmp/nvim-linux64.tar.gz"
    mode: '0644'

- name: Extract Neovim to /opt
  become: true  # 🛠️ Add this line!
  unarchive:
    src: "/tmp/nvim-linux64.tar.gz"
    dest: "/opt/"
    remote_src: yes
    creates: "/opt/nvim-linux64"

- name: Symlink nvim to /usr/local/bin
  become: true
  file:
    src: "/opt/nvim-linux64/bin/nvim"
    dest: "/usr/local/bin/nvim"
    state: link
    force: true

